name: Build, Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build -t joshuasundance/langchain-streamlit-demo .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: joshuasundance
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      run: docker push joshuasundance/langchain-streamlit-demo:latest

  push-to-huggingface:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

    - name: Push to HuggingFace Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git push https://joshuasundance:$HF_TOKEN@huggingface.co/spaces/joshuasundance/langchain-streamlit-demo main
